import { Router } from "express";
import { authRoutes } from "../modules/auth/index.js";
import { profileRoutes, settingsRoutes } from "../modules/users/index.js";
import { warehouseRoutes } from "../modules/warehouses/index.js";
import { employeeRoutes, leaveRequestRoutes, payrollRoutes } from "../modules/employees/index.js";
import { weightMachineRoutes } from "../modules/weighment/index.js";
import { stockEntryRoutes, stockMovementRoutes } from "../modules/stock/index.js";
import { auditRoutes } from "../modules/audit/index.js";
import { itemRoutes, collectionRoutes, dispatchRoutes } from "../modules/inventory/index.js";
import { attendanceRoutes } from "../modules/attendance/index.js";
import { reportsRoutes } from "../modules/reports/index.js";
import { biomassVendorRoutes } from "../modules/biomass-vendors/index.js";
import { biomassBuyerRoutes } from "../modules/biomass-buyers/index.js";
import { purchaseRoutes } from "../modules/purchase/index.js";
import { salesRoutes } from "../modules/sales/index.js";
import { goodsRoutes } from "../modules/goods/index.js";
import { productsRoutes } from "../modules/products/index.js";
import { customerRoutes, vendorRoutes } from "../modules/customers/index.js";
import { alertRoutes } from "../modules/alerts/index.js";
import { dashboardRoutes } from "../modules/dashboard/index.js";

const router = Router();

router.use("/dashboard", dashboardRoutes);

router.use("/auth", authRoutes);
router.use("/profiles", profileRoutes);
router.use("/settings", settingsRoutes);
router.use("/warehouses", warehouseRoutes);
router.use("/employees", employeeRoutes);
router.use("/leave-requests", leaveRequestRoutes);
router.use("/payroll", payrollRoutes);
router.use("/weight-machines", weightMachineRoutes);
router.use("/stock-entries", stockEntryRoutes);
router.use("/stock-movements", stockMovementRoutes);
router.use("/audit-logs", auditRoutes);
router.use("/items", itemRoutes);
router.use("/collections", collectionRoutes);
router.use("/dispatches", dispatchRoutes);
router.use("/attendance", attendanceRoutes);
router.use("/reports", reportsRoutes);
router.use("/biomass-vendors", biomassVendorRoutes);
router.use("/biomass-buyers", biomassBuyerRoutes);
router.use("/purchase-orders", purchaseRoutes);
router.use("/sales-invoices", salesRoutes);
router.use("/goods", goodsRoutes);
router.use("/products", productsRoutes);
router.use("/customers", customerRoutes);
router.use("/vendors", vendorRoutes);
router.use("/alerts", alertRoutes);

export default router;
